USE INFINITY;

SHOW TABLES;

CREATE TABLE IF NOT EXISTS USERS(
	LOGIN varchar(10) NOT NULL UNIQUE PRIMARY KEY,
    FULL_NAME VARCHAR(30) NOT NULL
    );
    
SET GLOBAL LOCAL_INFILE = true;

LOAD DATA LOCAL INFILE 'c:\\temp\\users.csv' INTO TABLE USERS 
FIELDS TERMINATED BY ';' LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM USERS;
